engines:
  eslint:
    enabled: false
  rubocop:
    enabled: false
    exclude_paths:
      - config/engines.yml
  duplication:
    enabled: true
    exclude_paths:
      - config/engines.yml
  metrics:
    enabled: true
    exclude_paths:
      - config/engines.yml
  coverage:
    enabled: true
    exclude_paths:
      - config/engines.yml
 languages:
   css:
     extensions:
       - '-css.resource'
 
